# Generated by Django 2.2.17 on 2021-04-05 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='averageRating',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
