# Generated by Django 2.2.17 on 2021-04-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0002_auto_20210407_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
