# Generated by Django 2.2.17 on 2021-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0002_auto_20210405_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reviews',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
