# Generated by Django 2.2.17 on 2021-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0002_auto_20210406_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
