# Generated by Django 3.1.7 on 2021-04-06 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0003_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='averageRating',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
