# Generated by Django 2.2.17 on 2021-04-07 09:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0003_auto_20210407_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='commentID',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 7)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='author',
            field=models.BooleanField(default=False),
        ),
    ]
