# Generated by Django 2.2.17 on 2021-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0004_auto_20210406_1342'),
        ('article_reviewer', '0004_auto_20210406_1225'),
    ]

    operations = [
    ]
