# Generated by Django 3.1.7 on 2021-04-06 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_reviewer', '0005_merge_20210406_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reviews',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
